---
title: "FullMarkdown"
output: html_document
date: "2026-06-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#packages
library(phyloseq)
library(ggplot2)
library(tidyverse)
library(vegan)
library(dbstats)
library(qiime2R)
library(biomformat)
library(microbiome)
library(ape)
library(ARTool)
library(readr)
library(lme4)
library(gamm4)
library(ggpubr)

```

```{r}
#soil chemistry and pH
ChemData=read.csv("Chemical.csv")
pHData=read.csv("pH.csv")
pHChange=read.csv("pHChange.csv")

ChemData$Treatment <- factor(ChemData$Treatment)
ChemData$Plot      <- factor(ChemData$Plot)

#pH
pHmodel <- lmer(pH ~ Treatment * Time + (1 | Plot/Row), data = pHData)
summary(pHmodel)

df_summary <- pHData %>%
  group_by(Treatment, Plot) %>%
  summarise(
    n = n(),
    mean = mean(pH, na.rm = TRUE),
    sd = sd(pH, na.rm = TRUE),
    se = sd / sqrt(n),
    .groups = "drop"
  )

pHData$Date <- factor(pHData$Date, levels = unique(pHData$Date))

ggplot(pHData, aes(x = Date, y = pH, color = Treatment, linetype = Plot, group = Row)) +
  geom_line(alpha = 0.4) +
  stat_summary(aes(group = Treatment), fun = mean, geom = "line", size = 1.5) +
  labs(title = "",
       x = "",
       y = "pH") +
  theme_minimal()  + scale_color_manual(values = c("Control" = "purple4",
                                "Treatment" = "darkgoldenrod3"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, color = "black")) 

#Phosphorous
#non parametric model 
Pmodel_art <- art(P ~ Treatment * Plot, data = ChemData)
anova(Pmodel_art)

ChemData %>%
 ggplot(aes(x = Plot, y = P, fill = Treatment)) +
 geom_boxplot(outlier.shape = NA, alpha = 0.8, position = position_dodge(width = 0.8)) +
 geom_jitter(aes(fill = Treatment), color="black",
              shape = 21,  
              stroke = 0.5, 
              size = 2.5,
              alpha = 0.8,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)) +
  xlab("Plot") +
  ylab("Available Phosphorous") +
  theme_classic(base_size = 14) +
  scale_fill_viridis_d(name = "Treatment", labels = c("Control", "Treatment"))

#CaCO3
#non parametric model 
CaCO3model_art <- art(CaCO3 ~ Treatment * Plot, data = ChemData)
anova(CaCO3model_art)

ChemData %>%
 ggplot(aes(x = Plot, y = CaCO3, fill = Treatment)) +
 geom_boxplot(outlier.shape = NA, alpha = 0.8, position = position_dodge(width = 0.8)) +
geom_jitter(aes(fill = Treatment), color="black",
              shape = 21,  
              stroke = 0.5,
              size = 2.5,
              alpha = 0.8,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)) +
  xlab("Plot") +
  ylab("Calcium carbonate equivalent") +
  theme_classic(base_size = 14) +
  scale_fill_viridis_d(name = "Treatment", labels = c("Control", "Treatment"))

#means and SE
ChemData %>%
  group_by(Treatment) %>%
  summarise(
    meanCa = mean(CaCO3, na.rm = TRUE),
    sdCa   = sd(CaCO3, na.rm = TRUE),
    n      = sum(!is.na(CaCO3)),
    seCa   = sdCa / sqrt(n),
    meanP = mean(P, na.rm = TRUE))



```

```{r}
#Does S as an acidifier result in changes to soil microbial community diversity?
#uploading
metadata<-read_q2metadata("seq-metadata.tsv")
ITS_tableB <- read_tsv("ITSB-table.tsv")
Bac_tableB <- read_tsv("16SB-table.tsv")


ITS_simpson = read_tsv("ITS-simpson.tsv")
Bac_simpson = read_tsv("16S-simpson.tsv")

ITS_Shannon<-read_tsv("ITS-shannon-bootstrapped.tsv")
Bac_Shannon<-read_tsv("16S-shannon-bootstrapped.tsv")

CombinedMetadata<-read_tsv("CombinedMetadata.tsv")

Bac_Bray <- read.delim("16SB-Bray.tsv", row.names=1)
Bac_Jacc <- read.delim("16SB-Jacc.tsv", row.names=1)
ITS_Bray <- read.delim("ITSB-Bray.tsv", row.names=1)
ITS_Jacc <- read.delim("ITSB-Jacc.tsv", row.names=1)


MetadataB<-
metadata %>% 
  left_join(Bac_simpson)

MetadataB<-
MetadataB %>% 
  left_join(Bac_Shannon)

MetadataF<-
metadata %>% 
  left_join(ITS_simpson)

MetadataF <- 
  MetadataF %>% 
  left_join(ITS_Shannon)



#alpha diversity 
#Simpson dominance
CombinedMetadata %>%
  filter(year=="2024") %>%
  ggplot(aes(x = Kingdom, y = simpsons_dominance, fill = treatment)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.8, position = position_dodge(width = 0.8)) +
  geom_jitter(aes(fill = treatment), color="black",
              shape = 21,  
              stroke = 0.5,
              size = 2.5,
              alpha = 0.8,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)) +
  xlab("") +
  ylab("Simpson Dominance") +
  theme_classic(base_size = 14) +
  scale_fill_viridis_d(name = "Treatment") +
  scale_color_viridis_d(name = "Treatment")

#Shannon
CombinedMetadata %>%
  filter(year=="2024") %>%
  ggplot(aes(x = Kingdom, y = shannon_entropy, fill = treatment)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.8, position = position_dodge(width = 0.8)) +
  geom_jitter(aes(fill = treatment), color="black",
              shape = 21,  
              stroke = 0.5, 
              size = 2.5,
              alpha = 0.8,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)) +
  xlab("") +
  ylab("Shannon Diversity") +
  theme_classic(base_size = 14) +
  scale_fill_viridis_d(name = "Treatment") +
  scale_color_viridis_d(name = "Treatment")

#models
metadataBb=MetadataB %>%
  subset(year=="2024")

metadataFb=MetadataF %>%
  subset(year=="2024")

SimpModelFb <- lmer(simpsons_dominance ~ treatment + (1 | plot), data = metadataFb)
summary(SimpModelFb)
ShanModelFb <- lmer(shannon_entropy ~ treatment + (1 | plot), data = metadataFb)
summary(ShanModelFb)

SimpModelBb <- lmer(simpsons_dominance ~ treatment + (1 | plot), data = metadataBb)
summary(SimpModelBb)
ShanModelBb <- lmer(shannon_entropy ~ treatment + (1 | plot), data = metadataBb)
summary(ShanModelBb)



#beta diversity 
#ITS 
#Bray
ITSBrayWB_dist <- as.dist(ITS_Bray)

ITSB_BrayDispersion <- betadisper(ITSBrayWB_dist, metadataFb$treatment)
  ITSB_BrayWStats <- permutest(ITSB_BrayDispersion, permutations = 999)
  
  #PCoA
ITSB_pcoa_coords <- cmdscale(ITS_Bray, eig = TRUE, k = 2)
ITSB_points_df <- as.data.frame(ITSB_pcoa_coords$points)
colnames(ITSB_points_df) <- c("PCoA1", "PCoA2")
ITSB_points_df$SampleID <- rownames(ITSB_points_df)
ITSB_plot_df <- left_join(ITSB_points_df, metadataFb, by = "SampleID")

ggplot(ITSB_plot_df, aes(x = PCoA1, y = PCoA2, color = treatment)) +
  geom_point(size = 3, alpha = 0.8) +
  stat_ellipse(aes(group = treatment), linetype = 2, type = "t") +
  labs(title = "PCoA of Weighted Bray-Curtis Dissimilarity \nin Year 2 Fungal Communities",
       x = paste0("PCoA1 (", round(ITSB_pcoa_coords$eig[1] / sum(ITSB_pcoa_coords$eig) * 100, 1), "%)"),
       y = paste0("PCoA2 (", round(ITSB_pcoa_coords$eig[2] / sum(ITSB_pcoa_coords$eig) * 100, 1), "%)")) +
  theme_minimal() +
  theme(text = element_text(size = 14))

#Jaccard
ITSBrayUWB_dist <- as.dist(ITS_Jacc)

ITSB_BrayDispersion <- betadisper(ITSBrayUWB_dist, metadataFb$treatment)
  ITSB_BrayUWStats <- permutest(ITSB_BrayDispersion, permutations = 999)

  #PCoA
ITSB_pcoa_coords <- cmdscale(ITS_Jacc, eig = TRUE, k = 2)
ITSB_points_df <- as.data.frame(ITSB_pcoa_coords$points)
colnames(ITSB_points_df) <- c("PCoA1", "PCoA2")
ITSB_points_df$SampleID <- rownames(ITSB_points_df)
ITSB_plot_df <- left_join(ITSB_points_df, metadataFb, by = "SampleID")

ggplot(ITSB_plot_df, aes(x = PCoA1, y = PCoA2, color = treatment)) +
  geom_point(size = 3, alpha = 0.8) +
  stat_ellipse(aes(group = treatment), linetype = 2, type = "t") +
  labs(title = "PCoA of Unweighted Bray-Curtis Dissimilarity \nin Year 2 Fungal Communities",
       x = paste0("PCoA1 (", round(ITSB_pcoa_coords$eig[1] / sum(ITSB_pcoa_coords$eig) * 100, 1), "%)"),
       y = paste0("PCoA2 (", round(ITSB_pcoa_coords$eig[2] / sum(ITSB_pcoa_coords$eig) * 100, 1), "%)")) +
  theme_minimal() +
  theme(text = element_text(size = 14))





#16S 
#Bray
BacBrayWB_dist <- as.dist(Bac_Bray)

BacB_BrayDispersion <- betadisper(BacBrayWB_dist, metadataBb$treatment)
  BacB_BrayWStats <- permutest(BacB_BrayDispersion, permutations = 999)

  #PCoA
BacB_pcoa_coords <- cmdscale(Bac_Bray, eig = TRUE, k = 2)
BacB_points_df <- as.data.frame(BacB_pcoa_coords$points)
colnames(BacB_points_df) <- c("PCoA1", "PCoA2")
BacB_points_df$SampleID <- rownames(BacB_points_df)
BacB_plot_df <- left_join(BacB_points_df, metadataBb, by = "SampleID")

ggplot(BacB_plot_df, aes(x = PCoA1, y = PCoA2, color = treatment)) +
  geom_point(size = 3, alpha = 0.8) +
  stat_ellipse(aes(group = treatment), linetype = 2, type = "t") +
  labs(title = "PCoA of Weighted Bray-Curtis Dissimilarity \nin Year 2 Bacteria Communities",
       x = paste0("PCoA1 (", round(BacB_pcoa_coords$eig[1] / sum(BacB_pcoa_coords$eig) * 100, 1), "%)"),
       y = paste0("PCoA2 (", round(BacB_pcoa_coords$eig[2] / sum(BacB_pcoa_coords$eig) * 100, 1), "%)")) +
  theme_minimal() +
  theme(text = element_text(size = 14))


#Jaccard
BacBrayUWB_dist <- as.dist(Bac_Jacc)

BacB_BrayDispersion <- betadisper(BacBrayUWB_dist, metadataBb$treatment)
  BacB_BrayUWStats <- permutest(BacB_BrayDispersion, permutations = 999)

BacB_pcoa_coords <- cmdscale(Bac_Jacc, eig = TRUE, k = 2)

# Get coordinates
BacB_points_df <- as.data.frame(BacB_pcoa_coords$points)
colnames(BacB_points_df) <- c("PCoA1", "PCoA2")

# Add SampleID if needed
BacB_points_df$SampleID <- rownames(BacB_points_df)

# Join with metadata
BacB_plot_df <- left_join(BacB_points_df, metadataBb, by = "SampleID")

ggplot(BacB_plot_df, aes(x = PCoA1, y = PCoA2, color = treatment)) +
  geom_point(size = 3, alpha = 0.8) +
  stat_ellipse(aes(group = treatment), linetype = 2, type = "t") +
  labs(title = "PCoA of Unweighted Bray-Curtis Dissimilarity \nin Year 2 Bacteria Communities",
       x = paste0("PCoA1 (", round(BacB_pcoa_coords$eig[1] / sum(BacB_pcoa_coords$eig) * 100, 1), "%)"),
       y = paste0("PCoA2 (", round(BacB_pcoa_coords$eig[2] / sum(BacB_pcoa_coords$eig) * 100, 1), "%)")) +
  theme_minimal() +
  theme(text = element_text(size = 14))


#beta models
FungiBrayWb=adonis2(ITS_Bray ~ treatment, data = metadataFb, permutations = 999, by = "terms", strata = metadataFb$plot)

FungiBrayUWb=adonis2(ITS_Jacc ~ treatment, data = metadataFb, permutations = 999, by = "terms", strata = metadataFb$plot)


BacBrayWb=adonis2(Bac_Bray ~ treatment, by = "terms",strata = metadataBb$plot, data = metadataBb,permutations = 999)

BacBrayUWb=adonis2(Bac_Jacc ~ treatment, by = "terms",strata = metadataBb$plot, data = metadataBb,permutations = 999)





#thiobacillus plot
ThioData=read.csv("Thiobacillus.csv")

ThioData

ggplot(ThioData, aes(x = factor(Year), y = Abundance, fill = Treatment)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  labs(
    title = "Thiobacillus abundance in control vs treated rows",
    x = "Year",
    y = "Abundance",
    fill = "Treatment")

```
```{r}
#Is pH or S driving changes to bacterial and fungal growth?
#Upload and filtering 
GrowthData=read.csv("GrowthData.csv")
GrowthDataGraph=read.csv("GrowthDataGraph.csv")

GrowthDataFungiS <- GrowthDataGraph %>%
  filter(Type == "Fungi" & (Test == "S" | Test == "ControlP"))
GrowthDataFungiS <- GrowthDataFungiS %>%
  filter(Isolate == "Alternaria sorghi" | Isolate == "Mortierella alpina" | Isolate == "Curvularia inaequalis")
GrowthDataFungiS$Treatment <- factor(
  GrowthDataFungiS$Treatment,
  levels = c("0mg | pH8.5", "2.5mg", "5mg", "7.5mg", "10mg"))

GrowthDataBacS=GrowthDataGraph %>%
  filter(Type == "Bacteria" & (Test == "S" | Test == "ControlP"))
GrowthDataBacS$Treatment <- factor(
  GrowthDataBacS$Treatment,
  levels = c("0mg | pH8.5", "2.5mg", "5mg", "7.5mg", "10mg"))

GrowthDataFungipH=GrowthDataGraph %>%
  filter(Type == "Fungi" & (Test == "pH" | Test == "ControlP"))
GrowthDataFungipH$Treatment <- factor(
  GrowthDataFungipH$Treatment,
  levels = c("pH6.5", "pH7", "pH7.5", "pH8", "0mg | pH8.5"))

GrowthDataBacpH=GrowthDataGraph %>%
  filter(Type == "Bacteria" & (Test == "pH" | Test == "ControlP"))
GrowthDataBacpH$Treatment <- factor(
  GrowthDataBacpH$Treatment,
  levels = c("pH6.5", "pH7", "pH7.5", "pH8", "0mg | pH8.5"))


# plots
GrowthDataBacS <- GrowthDataBacS %>%
  mutate(Isolate = factor(Isolate, levels = unique(Isolate),
                          labels = paste0("italic('", unique(Isolate), "')")))

GrowthDataFungiS <- GrowthDataFungiS %>%
  mutate(Isolate = factor(Isolate, levels = unique(Isolate),
                          labels = paste0("italic('", unique(Isolate), "')")))

GrowthDataFungipH <- GrowthDataFungipH %>%
  mutate(Isolate = factor(Isolate, levels = unique(Isolate),
                          labels = paste0("italic('", unique(Isolate), "')")))

SummaryData <- GrowthDataBacS %>%
  group_by(Treatment, Isolate) %>%
  summarise(
    mean_Max = mean(Max, na.rm = TRUE),
    se_Max = sd(Max, na.rm = TRUE) / sqrt(n()),
    .groups = "drop")

BacMax_S <- ggplot(SummaryData, aes(x = Treatment, y = mean_Max, color = Isolate, group = Isolate)) +
  geom_line(position = position_dodge(width = 0.9), size = 1) +
  geom_point(position = position_dodge(width = 0.9), size = 2, shape = 21, fill = "white") +
  geom_errorbar(aes(ymin = mean_Max - se_Max, ymax = mean_Max + se_Max),
                width = 0.2,
                position = position_dodge(width = 0.9)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, face = "bold", color = "black")) +
  labs(x = "S Treatment",
       y = expression("Max OD 600"),
       title = "Bacterial isolate-specific max growth (OD 600) across S treatments") +
  geom_vline(xintercept = 1:length(unique(GrowthDataFungipH$Treatment)) + 0.5,
             linetype = "dashed", color = "grey") +
  scale_color_discrete(name = "Isolate", labels = function(x) parse(text = x))

BacMax_S


SummaryFungi_S <- GrowthDataFungiS %>%
  group_by(Treatment, Isolate) %>%
  summarise(
    mean_Slope = mean(Slope, na.rm = TRUE),
    se_Slope = sd(Slope, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )

FungiGrowth_S <- ggplot(SummaryFungi_S, aes(x = Treatment, y = mean_Slope, color = Isolate, group = Isolate)) +
  geom_line(position = position_dodge(width = 0.9), size = 1) +
  geom_point(position = position_dodge(width = 0.9), size = 2, shape = 21, fill = "white") +
  geom_errorbar(aes(ymin = mean_Slope - se_Slope, ymax = mean_Slope + se_Slope),
                width = 0.2,
                position = position_dodge(width = 0.9)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, face = "bold", color = "black")) +
  labs(x = "S Treatment",
       y = expression("Growth rate (h"^-1*")"),
       title = "Fungal isolate-specific growth rate across S treatments") +
  geom_vline(xintercept = 1:length(unique(GrowthDataFungipH$Treatment)) + 0.5,
             linetype = "dashed", color = "grey") +
  scale_color_discrete(name = "Isolate", labels = function(x) parse(text = x))

FungiGrowth_S


SummaryFungi_pH <- GrowthDataFungipH %>%
  group_by(Treatment, Isolate) %>%
  summarise(
    mean_Slope = mean(Slope, na.rm = TRUE),
    se_Slope = sd(Slope, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )

SummaryFungi_pH$Treatment <- factor(SummaryFungi_pH$Treatment, 
                                   levels = c("0mg | pH8.5", "pH8", "pH7.5", 'pH7', 'pH6.5'))

FungiSlope_pH <- ggplot(SummaryFungi_pH, aes(x = Treatment, y = mean_Slope, color = Isolate, group = Isolate)) +
  geom_line(position = position_dodge(width = 0.9), size = 1) +
  geom_point(position = position_dodge(width = 0.9), size = 2, shape = 21, fill = "white") +
  geom_errorbar(aes(ymin = mean_Slope - se_Slope, ymax = mean_Slope + se_Slope),
                width = 0.2,
                position = position_dodge(width = 0.9)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, face = "bold", color = "black")) +
  labs(x = "pH Treatment",
       y = expression("Growth rate (h"^-1*")"),
       title = "Fungal isolate-specific growth rate across pH treatments") +
  geom_vline(xintercept = 1:length(unique(GrowthDataFungipH$Treatment)) + 0.5,
             linetype = "dashed", color = "grey") +
  scale_color_discrete(name = "Isolate", labels = function(x) parse(text = x))

FungiSlope_pH

#full models with model selection/simplification 
#bacteria slope
Lmer1=lmer(Slope~Treatment+(1+Treatment|Isolate), data=GrowthDataBacpH,na.action = na.omit)
summary(Lmer1)

Lmer2=lmer(Slope~Treatment+(1+Treatment|Isolate), data=GrowthDataBacS,na.action = na.omit)
summary(Lmer2)

#fungi slope
Lmer3=lmer(Slope~Treatment+(1+Treatment|Isolate), data=GrowthDataFungipH,na.action = na.omit)
summary(Lmer3)

Lmer4=lmer(Slope~Treatment+(1+Treatment|Isolate), data=GrowthDataFungiS,na.action = na.omit)
Lmer4Simple <-lmer(Slope~Treatment+(1|Isolate),data =GrowthDataFungiS,na.action = na.omit)
summary(Lmer4Simple) #
anova(Lmer4, Lmer4Simple) 

#bacteria max
Lmer5=lmer(Max~Treatment+(1+Treatment|Isolate), data=GrowthDataBacpH,na.action = na.omit)
Lmer5Simple=lmer(Max~Treatment+(1|Isolate), data=GrowthDataBacpH,na.action = na.omit)
summary(Lmer5Simple)
anova(Lmer5, Lmer5Simple)

Lmer6=lmer(Max~Treatment+(1+Treatment|Isolate), data=GrowthDataBacS,na.action = na.omit)
Lmer6Simple=lmer(Max~Treatment+(1|Isolate), data=GrowthDataBacS,na.action = na.omit)
summary(Lmer6Simple) #**
anova(Lmer6, Lmer6Simple)

#fungi max
Lmer7=lmer(Max~Treatment+(1+Treatment|Isolate), data=GrowthDataFungipH,na.action = na.omit)
Lmer7Simple=lmer(Max~Treatment+(1|Isolate), data=GrowthDataFungipH,na.action = na.omit)
summary(Lmer7Simple)
anova(Lmer7, Lmer7Simple)

Lmer8=lmer(Max~Treatment+(1+Treatment|Isolate), data=GrowthDataFungiS,na.action = na.omit)
Lmer8Simple=lmer(Max~Treatment+(1|Isolate), data=GrowthDataFungiS,na.action = na.omit)
summary(Lmer8Simple)
Lm8=lm(Max ~ Treatment, data = GrowthDataFungiS,na.action = na.omit)
summary(Lm8)
anova(Lmer8, Lmer8Simple, Lm8)
```
```{r}
#Does S result in changes to microbial decomposition rate?
WeightData=read.csv("TeaData.csv")

#model
WeightData$Treatment <- as.factor(WeightData$Treatment)
WeightGAMM <- gamm4(Weight ~ Treatment + s(Time, k = 4),
  random = ~(1 | Plot/Row), data = WeightData)

WeightData <- WeightData %>%
  mutate(predicted = predict(WeightGAMM$gam, newdata = .))

#plot
compare_data <- WeightData %>%
  group_by(Time, Treatment) %>%
  summarise(
    mean_obs = mean(Weight, na.rm = TRUE),
    se_obs = sd(Weight, na.rm = TRUE) / sqrt(n()),
    mean_pred = mean(predicted, na.rm = TRUE),
    .groups = "drop"
  )

new_data <- expand.grid(
  Time = seq(min(WeightData$Time), max(WeightData$Time), length.out = 200),
  Treatment = unique(WeightData$Treatment)
)

months=c("October 2023","October 2023", "June 2024","June 2024", "July 2024", "July 2024", "August 2024", "August 2024", "Sept 2024", "Sept 2024")

compare_data <- compare_data %>%
  mutate(Month = months)

compare_data$Month <- factor(
compare_data$Month,
  levels = c("October 2023", "June 2024","July 2024", "August 2024", "Sept 2024"))

ggplot(compare_data, aes(x = Month, y = mean_obs, color = Treatment, group = Treatment)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = mean_obs - se_obs,ymax = mean_obs + se_obs), width = 0.2) +
  labs(title = "Observed Means with Error Bars", x = "", y = "Weight (g)") +
  theme_minimal() +
  scale_color_viridis_d(labels = c("Control", "Sulfur treated")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, face = "bold", color = "black"))

```
```{r}
#Does S change plant diversity?
#Upload
DivData=read.csv("PlantDiv.csv")
PlantMetadata <- read_q2metadata("PlantMetadata.tsv") %>%
column_to_rownames("SampleID")
BioData=read.csv("Biodiversity.csv")
BioData$uniID <- paste(BioData$Row, BioData$Sample)

#models
#shannon
ShanModel=lmer(Shannon~Treatment + (1|Plot:Row), data=DivData, na.action = na.fail)
summary(ShanModel)

#simpson
SimpModel=lmer(Simpson~Treatment+ (1|Plot:Row), data=DivData, na.action = na.fail)
summary(SimpModel)


#plots
ShanPlot=DivData %>%
  filter(!is.na(Shannon)) %>%
  ggplot(aes(x = Treatment, y = Shannon, fill = Treatment)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.8, position = position_dodge(width = 0.8)) +
  geom_jitter(aes(fill = Treatment), color="black",
              shape = 21,  # shape 21 supports both fill and stroke
              stroke = 0.5, # outline thickness
              size = 2.5,
              alpha = 0.8,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)) +
  xlab("") +
  ylab("Shannon Richness") +
  theme_classic(base_size = 14) +
  scale_fill_viridis_d(name = "Treatment") +
  scale_color_viridis_d(name = "Treatment")

SimpPlot=DivData %>%
  filter(!is.na(Simpson)) %>%
  ggplot(aes(x = Treatment, y = Simpson, fill = Treatment)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.8, position = position_dodge(width = 0.8)) +
  geom_jitter(aes(fill = Treatment), color="black",
              shape = 21,  # shape 21 supports both fill and stroke
              stroke = 0.5, # outline thickness
              size = 2.5,
              alpha = 0.8,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)) +
  xlab("") +
  ylab("Simpson Evenness") +
  theme_classic(base_size = 14) +
  scale_fill_viridis_d(name = "Treatment") +
  scale_color_viridis_d(name = "Treatment")

ggarrange(ShanPlot,SimpPlot, ncol=2, common.legend = TRUE, legend="bottom")

#beta diversity 
BioData$Row <- as.factor(BioData$Row)
BioDataWide <- BioData %>% dplyr::select(uniID, Species, Count) 
BioDataWide <- BioDataWide %>% group_by(uniID, Species) %>% summarise(Count = sum(Count)) 

comm <- BioDataWide %>% spread(Species, Count)
comm[2:18] <- lapply(comm[2:18], as.numeric)
comm=comm %>%
  column_to_rownames("uniID")

BetaDivWide <- decostand(comm[2:18], method = "pa")

Bray <- vegdist(BetaDivWide, method = "bray", binary = TRUE)
Jaccard <- vegdist(BetaDivWide, method = "jaccard", binary = TRUE)


PlantBetaBray=adonis2(Bray ~ treatment, data = PlantMetadata)
PlantBetaJaccard=adonis2(Jaccard ~ treatment, data = PlantMetadata)
```

